// Code generated by Slice Machine. DO NOT EDIT.

export const components = {
  bento: () => import("~/slices/Bento/index.vue"),
  call_to_action: () => import("~/slices/CallToAction/index.vue"),
  case_studies: () => import("~/slices/CaseStudies/index.vue"),
  hero: () => import("~/slices/Hero/index.vue"),
  integrations: () => import("~/slices/Integrations/index.vue"),
  rich_text: () => import("~/slices/RichText/index.vue"),
  showcase: () => import("~/slices/Showcase/index.vue"),
}
